node {
  def commit_id
  stage('step a') {
    checkout scm
    sh 'git rev-parse --short HEAD > .git/commit-id'
    commit_id = readFile('.git/commit-id').trim()
  }
  stage('DockerBuild') {
    dir('advance/multistage_build') {
      sh 'docker build --target builder -t roysav/ci-cd:multi_stage_builder -f Dockerfile-pipelines .'
    }
  }
  stage('Linting') {
  }
}
  stage('Push') {
  withCredentials([string(credetianalsId: 'docker', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
        dir('advance/multistage_build') {
        sh 'docker build --target linting -t roysav/ci-cd:multi_stage_test -f Dockerfile-pipelines .'
        sh "docker login -u $USERNAME -p $PASSWORD"
        sh 'docker push roysav/ci-cd:multi_stage_test'
        }
  }
   }
