node {
  def commit_id
  stage('step a') {
    checkout scm
    sh 'git rev-parse --short HEAD > .git/commit-id'
    commit_id = readFile('.git/commit-id').trim()
  }
  stage('DockerBuild') {
    dir('docker/day_2/12factor/multistage_build/') {
      sh 'docker build --target builder -t roysav/ci-cd:multi_stage_builder -f Dockerfile-pipelines .'
    }
  }
  stage('Linting') {
  }
}
   withCredentials([string(credetianalsId: 'docker', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
  stage('Push') {
        dir('docker/day_2/12factor/multistage_build/') {
        sh 'docker build --target linting -t roysav/ci-cd:multi_stage_test -f Dockerfile-pipelines .'
        sh "docker login -u $USERNAME -p $PASSWORD"
        sh 'docker push roysav/ci-cd:multi_stage_test'
        }
  }
   }
