node {
  stage('step a') {
    checkout scm
    sh 'git rev-parse --short HEAD > .git/commit-id'
    readFile('.git/commit-id').trim()
  }
  stage('DockerBuild') {
    dir('advance/workshop') {
      sh 'docker build --target test -t roysav/ci-cd:multi_stage_builder .'
    }
  }
  stage('Linting') {
  }
  stage('Push') {
  withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
        dir('advance/workshop') {
        sh 'docker build -t roysav/ci-cd:multi_stage_test .'
        sh "docker login -u $USERNAME -p $PASSWORD"
        sh 'docker push roysav/ci-cd:multi_stage_test'
        }
  }
   }
}