node {
  stage('step a') {
    checkout scm
    sh 'git rev-parse --short HEAD > .git/commit-id'
    readFile('.git/commit-id').trim()
  }
  stage('DockerBuild') {
    dir('advance/workshop') {
      sh 'docker build --target test -t roysav/ci-cd:multi_stage_builder -f Dockerfile-pipelines .'
    }
  }
  stage('Linting') {
  }
  stage('Push') {
  withCredentials([usernamePassword(credentialsId: 'docker', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
        dir('advance/workshop') {
        sh 'DOCKER_BUILDKIT=0 docker build --network multistage_build_nexus -t roysav/ci-cd:multi_stage_test -f Dockerfile-pipelines .'
        sh "docker login -u $USERNAME -p $PASSWORD"
        sh 'docker push roysav/ci-cd:multi_stage_test'
        }
  }
   }
}